# A sample Gemfile
source "https://rubygems.org"

gem "sinatra"
gem "sinatra-contrib"
gem "memcache-client"
gem "foreman"
gem "unicorn"
gem "mysql2"
gem "rack", ">= 1.6.11"
gem "rack-protection", ">= 1.5.5"
gem "rack-flash3"
